-- Enable useful extensions
CREATE EXTENSION IF NOT EXISTS citext;

-- =====================================================================
-- Tags (normalized, hierarchical) + Join table + Aliases
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.tags (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          CITEXT NOT NULL UNIQUE,
  display_name  TEXT   NOT NULL,
  kind          TEXT,
  parent_tag_id BIGINT REFERENCES public.tags(id) ON DELETE SET NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Simple updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tags_set_updated_at ON public.tags;
CREATE TRIGGER tags_set_updated_at
BEFORE UPDATE ON public.tags
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.tag_aliases (
  alias_slug CITEXT PRIMARY KEY,
  tag_id     BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.question_tags (
  question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  tag_id      BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (question_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_question_tags_tag_id ON public.question_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_question_tags_question_id ON public.question_tags(question_id);

-- =====================================================================
-- Helper: slugify a free-text label into a URL-friendly slug
-- =====================================================================
CREATE OR REPLACE FUNCTION public.slugify(input TEXT)
RETURNS TEXT AS $$
DECLARE
  s TEXT;
BEGIN
  s := lower(trim(input));
  -- Replace all non-alphanumeric with dashes
  s := regexp_replace(s, '[^a-z0-9]+', '-', 'g');
  -- Collapse duplicate dashes
  s := regexp_replace(s, '-{2,}', '-', 'g');
  -- Trim leading/trailing dashes
  s := trim(both '-' from s);
  IF s IS NULL OR length(s) = 0 THEN
    RETURN NULL;
  END IF;
  RETURN s;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- =====================================================================
-- Helper: get-or-create a canonical tag for a topic label
-- =====================================================================
CREATE OR REPLACE FUNCTION public.get_or_create_tag_for_topic(topic_label TEXT)
RETURNS BIGINT AS $$
DECLARE
  v_slug TEXT;
  v_id   BIGINT;
BEGIN
  IF topic_label IS NULL OR length(btrim(topic_label)) = 0 THEN
    RETURN NULL;
  END IF;

  v_slug := public.slugify(topic_label);
  IF v_slug IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT id INTO v_id FROM public.tags WHERE slug = v_slug;
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  INSERT INTO public.tags(slug, display_name, kind)
  VALUES (v_slug::citext, trim(topic_label), 'topic')
  ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- Backfill: seed tags from existing questions.topic and link via question_tags
-- Safe to re-run (ON CONFLICT guards)
-- =====================================================================

-- Seed canonical tags
WITH distinct_topics AS (
  SELECT DISTINCT trim(topic) AS topic
  FROM public.questions
  WHERE topic IS NOT NULL AND trim(topic) <> ''
)
INSERT INTO public.tags(slug, display_name, kind)
SELECT public.slugify(topic)::citext, topic, 'topic'
FROM distinct_topics
ON CONFLICT (slug) DO NOTHING;

-- Link existing questions to tags
INSERT INTO public.question_tags(question_id, tag_id)
SELECT q.id, t.id
FROM public.questions q
JOIN public.tags t ON t.slug = public.slugify(q.topic)::citext
LEFT JOIN public.question_tags qt ON qt.question_id = q.id AND qt.tag_id = t.id
WHERE q.topic IS NOT NULL AND trim(q.topic) <> '' AND qt.question_id IS NULL
ON CONFLICT DO NOTHING;

-- =====================================================================
-- Trigger: when inserting a question with a topic, ensure tag + join exist
-- =====================================================================
CREATE OR REPLACE FUNCTION public.questions_topic_to_tag_join()
RETURNS TRIGGER AS $$
DECLARE
  v_tag_id BIGINT;
BEGIN
  IF NEW.topic IS NOT NULL AND length(trim(NEW.topic)) > 0 THEN
    v_tag_id := public.get_or_create_tag_for_topic(NEW.topic);
    IF v_tag_id IS NOT NULL THEN
      -- Link this question to the tag
      INSERT INTO public.question_tags(question_id, tag_id)
      VALUES (NEW.id, v_tag_id)
      ON CONFLICT DO NOTHING;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_questions_topic_to_tags ON public.questions;
CREATE TRIGGER trg_questions_topic_to_tags
AFTER INSERT ON public.questions
FOR EACH ROW EXECUTE FUNCTION public.questions_topic_to_tag_join();

-- =====================================================================
-- RPC: search_questions_by_tags
-- Finds questions matching any/all of the provided tag slugs (or aliases),
-- optionally including descendants in the tag hierarchy
-- =====================================================================
CREATE OR REPLACE FUNCTION public.search_questions_by_tags(
  tag_slugs        TEXT[],
  require_all      BOOLEAN DEFAULT FALSE,
  include_descendants BOOLEAN DEFAULT FALSE,
  limit_count      INTEGER DEFAULT 10
)
RETURNS SETOF public.questions
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  base_tag_ids   BIGINT[];
  tag_ids        BIGINT[];
  base_count     INTEGER := 0;
BEGIN
  IF tag_slugs IS NULL OR array_length(tag_slugs, 1) IS NULL OR array_length(tag_slugs, 1) = 0 THEN
    RETURN QUERY
      SELECT q.* FROM public.questions q
      ORDER BY q.used_count ASC, q.created_at DESC
      LIMIT GREATEST(1, limit_count);
    RETURN;
  END IF;

  -- Resolve slugs and aliases to canonical tag IDs (distinct)
  WITH base AS (
    SELECT t.id
    FROM public.tags t
    WHERE t.slug = ANY(tag_slugs)
    UNION
    SELECT a.tag_id
    FROM public.tag_aliases a
    WHERE a.alias_slug = ANY(tag_slugs)
  )
  SELECT array_agg(id), COUNT(*)
  INTO base_tag_ids, base_count
  FROM (SELECT DISTINCT id FROM base) x;

  IF base_tag_ids IS NULL OR base_count = 0 THEN
    -- No valid tags resolved; return empty set
    RETURN;
  END IF;

  IF include_descendants THEN
    WITH RECURSIVE expanded AS (
      SELECT unnest(base_tag_ids) AS id
      UNION ALL
      SELECT t.id
      FROM public.tags t
      JOIN expanded e ON t.parent_tag_id = e.id
    )
    SELECT array_agg(DISTINCT id)
    INTO tag_ids
    FROM expanded;
  ELSE
    tag_ids := base_tag_ids;
  END IF;

  -- Match questions by tag set
  RETURN QUERY
  WITH matched AS (
    SELECT qt.question_id, COUNT(DISTINCT qt.tag_id) AS matched_count
    FROM public.question_tags qt
    WHERE qt.tag_id = ANY(tag_ids)
    GROUP BY qt.question_id
  )
  SELECT q.*
  FROM public.questions q
  JOIN matched m ON m.question_id = q.id
  WHERE (require_all AND m.matched_count >= base_count)
     OR (NOT require_all AND m.matched_count >= 1)
  ORDER BY q.used_count ASC, q.created_at DESC
  LIMIT GREATEST(1, limit_count);
END;
$$;

-- Helpful indexes for the questions table commonly used ordering
CREATE INDEX IF NOT EXISTS idx_questions_used_count ON public.questions(used_count);
CREATE INDEX IF NOT EXISTS idx_questions_created_at ON public.questions(created_at DESC);

